<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
 Schema::table('ext_chatbot_conversations',function(Blueprint $t){ if(!Schema::hasColumn('ext_chatbot_conversations','summary'))$t->longText('summary')->nullable(); if(!Schema::hasColumn('ext_chatbot_conversations','summary_updated_at'))$t->timestamp('summary_updated_at')->nullable(); if(!Schema::hasColumn('ext_chatbot_conversations','archived_at'))$t->timestamp('archived_at')->nullable()->index(); if(!Schema::hasColumn('ext_chatbot_conversations','merged_into_id'))$t->unsignedBigInteger('merged_into_id')->nullable()->index(); if(!Schema::hasColumn('ext_chatbot_conversations','assigned_to'))$t->unsignedBigInteger('assigned_to')->nullable()->index(); if(!Schema::hasColumn('ext_chatbot_conversations','priority'))$t->string('priority',32)->default('normal')->index(); if(!Schema::hasColumn('ext_chatbot_conversations','sla_due_at'))$t->timestamp('sla_due_at')->nullable()->index(); });
 Schema::table('ext_chatbot_histories',function(Blueprint $t){ foreach([['delivery_status','string'],['provider_message_id','string'],['failure_reason','text'],['draft_status','string'],['structured_type','string']] as [$c,$type]) if(!Schema::hasColumn('ext_chatbot_histories',$c)) $type==='text'?$t->text($c)->nullable():$t->string($c)->nullable(); if(!Schema::hasColumn('ext_chatbot_histories','retry_count'))$t->unsignedInteger('retry_count')->default(0); if(!Schema::hasColumn('ext_chatbot_histories','delivered_at'))$t->timestamp('delivered_at')->nullable(); if(!Schema::hasColumn('ext_chatbot_histories','metadata'))$t->json('metadata')->nullable(); });
 if(!Schema::hasTable('ext_chatbot_participants'))Schema::create('ext_chatbot_participants',function(Blueprint $t){$t->id();$t->foreignId('conversation_id')->index();$t->string('type');$t->string('reference')->nullable();$t->string('display_name')->nullable();$t->json('metadata')->nullable();$t->timestamp('last_seen_at')->nullable();$t->timestamps();$t->unique(['conversation_id','type','reference'],'chatbot_participant_unique');});
 if(!Schema::hasTable('ext_chatbot_attachments'))Schema::create('ext_chatbot_attachments',function(Blueprint $t){$t->id();$t->foreignId('conversation_id')->nullable()->index();$t->foreignId('history_id')->nullable()->index();$t->string('disk');$t->text('path');$t->string('name');$t->string('mime_type')->nullable();$t->unsignedBigInteger('size')->default(0);$t->json('metadata')->nullable();$t->timestamps();});
 if(!Schema::hasTable('ext_chatbot_workflow_runs'))Schema::create('ext_chatbot_workflow_runs',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->string('workflow');$t->string('status')->index();$t->json('context')->nullable();$t->json('output')->nullable();$t->timestamp('started_at')->nullable();$t->timestamp('finished_at')->nullable();$t->timestamps();});
 if(!Schema::hasTable('ext_chatbot_structured_actions'))Schema::create('ext_chatbot_structured_actions',function(Blueprint $t){$t->id();$t->foreignId('conversation_id')->index();$t->foreignId('history_id')->nullable()->index();$t->string('type');$t->string('status')->default('pending')->index();$t->json('payload');$t->json('result')->nullable();$t->foreignId('approved_by')->nullable();$t->timestamp('approved_at')->nullable();$t->timestamp('executed_at')->nullable();$t->timestamps();});
 } public function down(): void { Schema::dropIfExists('ext_chatbot_structured_actions');Schema::dropIfExists('ext_chatbot_workflow_runs');Schema::dropIfExists('ext_chatbot_attachments');Schema::dropIfExists('ext_chatbot_participants'); }
};
