<?php

declare(strict_types=1);

return [
    'security' => [
        'credential_storage' => 'encrypted_database',
        'session_authority_secret' => env('CHATBOT_ECOMMERCE_SESSION_AUTHORITY_SECRET', ''),
        'session_authority_ttl_seconds' => 1800,
        'require_signed_public_sessions' => true,
        'allow_public_customer_identity_binding' => false,
        'strict_tenant_isolation' => true,
    ],
    'extension' => 'chatbot-ecommerce',
    'reliability' => [
        'scheduler_enabled' => true,
        'queue_tenant_context_required' => true,
        'webhooks' => [
            'queue' => 'chatbot-ecommerce-payment-webhooks',
            'max_attempts' => 5,
            'base_backoff_seconds' => 5,
            'maximum_backoff_seconds' => 300,
            'dead_letter_retention_days' => 365,
        ],
        'circuit_breaker' => [
            'enabled' => true,
            'failure_threshold' => 5,
            'cooldown_seconds' => 120,
        ],
        'lifecycle' => [
            'preserve_data_on_disable' => true,
            'preserve_data_on_uninstall' => true,
        ],
    ],
    'health_checks' => true,
    'logging' => true,
    'metrics' => true,
    'rest_api' => true,
    'webhooks' => true,
    'events' => true,
    'permissions' => true,
    'feature_flags' => [
        'enabled' => true,
        'runtime_v2' => true,
        'native_inventory' => true,
        'multi_location_inventory' => true,
        'native_cart_engine' => true,
        'cart_recovery' => true,
        'pricing_rules' => true,
        'advanced_coupons' => true,
        'immutable_pricing_snapshots' => true,
        'native_checkout' => true,
        'checkout_approval' => true,
        'shipping_quotes' => true,
        'shipping_zones' => true,
        'partial_fulfillment' => true,
        'tracking' => true,
        'tax_engine' => true,
        'tax_zones' => true,
        'customer_tax_exemptions' => true,
        'rental_hire_receivables' => true,
        'recurring_rental_charges' => true,
        'rental_payment_allocations' => true,
        'rental_receipts' => true,
        'payment_engine' => true,
        'payment_webhooks' => true,
        'payment_refunds' => true,
        'native_shopping' => true,
        'marketplace_assisted_shopping' => true,
        'bnpl_payments' => true,
        'bnpl_marketplace_handoff' => true,
        'conversational_context' => true,
        'plain_english_failures' => true,
        'budget_locks' => true,
        'conversational_cards' => true,
        'native_orders' => true,
        'native_returns' => true,
        'action_rollback' => true,
        'three_role_commerce' => true,
        'customer_communications' => true,
        'customer_message_triage' => true,
        'customer_support_approvals' => true,
        'human_handoff' => true,
        'marketplace_read_mode' => true,
        'marketplace_order_import' => true,
        'marketplace_write_safety' => true,
        'marketplace_write_approvals' => true,
        'marketplace_write_rollback' => true,
        'marketplace_inventory_conflicts' => true,
        'marketplace_bulk_operations' => true,
        'marketplace_bulk_dry_run' => true,
        'marketplace_bulk_partial_rollback' => true,
        'listing_intelligence' => true,
        'marketplace_compliance' => true,
        'brand_voice_profiles' => true,
        'evidence_backed_claims' => true,
        'safe_listing_rewrites' => true,
        'inventory_conflict_resolution' => true,
        'marketplace_inventory_mappings' => true,
        'reservation_aware_channel_allocation' => true,
        'inventory_conflict_history' => true,
        'registered_scheduler' => true,
        'tenant_aware_queues' => true,
        'asynchronous_payment_webhooks' => true,
        'provider_circuit_breakers' => true,
        'lifecycle_state_management' => true,
        'unified_order_workbench' => true,
        'settlement_reconciliation' => true,
        'order_exception_management' => true,
    ],
    'listing_intelligence' => [
        'enabled' => true,
        'require_evidence_for_claims' => true,
        'block_on_compliance_findings' => true,
        'maximum_brand_examples' => 20,
        'maximum_claims' => 200,
        'maximum_rules_per_storefront' => 500,
        'supported_providers' => ['amazon', 'ebay', 'etsy', 'generic'],
    ],
    'marketplaces' => [
        'dispatch_mode' => env('CHATBOT_ECOMMERCE_MARKETPLACE_DISPATCH_MODE', 'sync'),
        'search_cache_ttl_seconds' => 300,
        'maximum_results_per_provider' => 50,
        'order_import_batch_size' => 100,
        'write' => [
            'marketplace_write_mode' => env('CHATBOT_ECOMMERCE_MARKETPLACE_WRITE_MODE', 'approval_only'),
            'dispatch_mode' => env('CHATBOT_ECOMMERCE_MARKETPLACE_WRITE_DISPATCH_MODE', 'sync'),
            'approval_secret' => env('CHATBOT_ECOMMERCE_MARKETPLACE_WRITE_APPROVAL_SECRET', ''),
            'approval_ttl_minutes' => 10,
            'maximum_snapshot_age_seconds' => 300,
            'maximum_writes_per_minute' => 10,
            'require_approval' => true,
            'allow_bulk_writes' => (bool) env('CHATBOT_ECOMMERCE_MARKETPLACE_ALLOW_BULK_WRITES', false),
            'bulk' => [
                'maximum_items' => 250,
                'approval_ttl_minutes' => 15,
                'continue_on_item_failure' => true,
                'partial_rollback_enabled' => true,
            ],
            'allow_inventory_oversell' => false,
            'allowed_operations' => ['update_listing', 'update_price', 'update_inventory', 'pause_listing', 'resume_listing'],
        ],
        'inventory_reconciliation' => [
            'enabled' => true,
            'source_of_truth' => 'internal',
            'resolution_mode' => 'suggest_only',
            'supported_resolution_modes' => ['observe_only', 'suggest_only', 'auto_prepare'],
            'allocation_mode' => 'equal_share',
            'maximum_sync_age_seconds' => 300,
            'quantity_tolerance' => 0,
            'buffer_quantity' => 0,
            'maximum_auto_delta' => 0,
            'auto_map_by_sku' => true,
            'never_auto_execute' => true,
            'queue' => 'chatbot-ecommerce-inventory-reconciliation',
            'scan_batch_size' => 100,
        ],
        'providers' => [
            'amazon' => [
                'gateway_url' => env('CHATBOT_ECOMMERCE_AMAZON_GATEWAY_URL', ''),
                'gateway_secret' => env('CHATBOT_ECOMMERCE_AMAZON_GATEWAY_SECRET', ''),
                'connect_timeout_seconds' => 5, 'timeout_seconds' => 20, 'retries' => 2, 'retry_delay_ms' => 250,
            ],
            'ebay' => [
                'gateway_url' => env('CHATBOT_ECOMMERCE_EBAY_GATEWAY_URL', ''),
                'gateway_secret' => env('CHATBOT_ECOMMERCE_EBAY_GATEWAY_SECRET', ''),
                'connect_timeout_seconds' => 5, 'timeout_seconds' => 20, 'retries' => 2, 'retry_delay_ms' => 250,
            ],
            'etsy' => [
                'gateway_url' => env('CHATBOT_ECOMMERCE_ETSY_GATEWAY_URL', ''),
                'gateway_secret' => env('CHATBOT_ECOMMERCE_ETSY_GATEWAY_SECRET', ''),
                'connect_timeout_seconds' => 5, 'timeout_seconds' => 20, 'retries' => 2, 'retry_delay_ms' => 250,
            ],
            'generic' => [
                'gateway_url' => env('CHATBOT_ECOMMERCE_GENERIC_MARKETPLACE_GATEWAY_URL', ''),
                'gateway_secret' => env('CHATBOT_ECOMMERCE_GENERIC_MARKETPLACE_GATEWAY_SECRET', ''),
                'connect_timeout_seconds' => 5, 'timeout_seconds' => 20, 'retries' => 2, 'retry_delay_ms' => 250,
            ],
        ],
    ],
    'conversation_context' => [
        'ttl_hours' => 24,
        'maximum_active_products' => 50,
        'maximum_pending_actions' => 20,
    ],
    'search_cache_ttl_seconds' => 300,
    'customer_communications' => [
        'auto_reply_enabled' => false,
        'auto_reply_confidence' => 0.90,
        'action_ttl_minutes' => 15,
        'automatic_refund_limit' => 0,
        'automatic_discount_limit' => 0,
        'automatic_store_credit_limit' => 0,
        'automatic_replacement_limit' => 0,
        'automatic_cancellation_limit' => 0,
        'currency' => 'USD',
        'require_identity_for_order_data' => true,
        'human_handoff' => true,
        'maximum_message_length' => 20000,
        'maximum_attachments' => 20,
        'enabled_channels' => ['web', 'email', 'sms', 'whatsapp', 'telegram', 'messenger', 'instagram', 'marketplace_message', 'internal_inbox'],
        'human_only_triggers' => ['legal_threat', 'fraud_suspected', 'chargeback_dispute', 'safety_incident', 'regulatory_complaint'],
    ],
    'order_workbench' => [
        'enabled' => true,
        'fulfillment_delay_seconds' => 172800,
        'proposal_ttl_minutes' => 30,
        'maximum_settlement_entries_per_import' => 1000,
        'external_orders_remain_authoritative' => true,
        'auto_resolve_absent_exceptions' => true,
    ],
    'orders' => [
        'return_window_days' => 30,
        'require_payment_capture' => true,
    ],
    'inventory' => [
        'default_reservation_ttl_minutes' => 15,
        'maximum_reservation_ttl_minutes' => 120,
        'expiration_batch_size' => 500,
    ],
    'cart' => [
        'active_ttl_days' => 7,
        'abandoned_ttl_days' => 30,
        'expiration_batch_size' => 500,
        'maximum_line_quantity' => 999,
    ],
    'checkout' => [
        'ttl_minutes' => 30,
        'approval_ttl_minutes' => 15,
        'payment_ttl_minutes' => 30,
        'expiration_batch_size' => 500,
        'allow_client_shipping_quotes' => false,
        'delivery_options' => [
            'pickup' => ['method' => 'pickup', 'name' => 'Pickup', 'amount' => 0],
            'digital' => ['method' => 'digital', 'name' => 'Digital delivery', 'amount' => 0],
        ],
    ],
    'shipping' => [
        'quote_ttl_minutes' => 15,
        'expiration_batch_size' => 500,
    ],
    'fulfillment' => [
        'require_tracking_for_delivery' => false,
    ],
    'tax' => [
        'provider' => 'internal',
        'default_zone' => null,
        'require_address_for_zoned_rates' => false,
        'maximum_rate_bps' => 100000,
    ],
    'payments' => [
        'provider' => 'internal',
        'intent_ttl_minutes' => 30,
        'expiration_batch_size' => 500,
        'webhook_tolerance_seconds' => 300,
        'allowed_methods' => ['card', 'direct_debit', 'bank_transfer', 'payid', 'cash', 'external', 'bnpl'],
        'instructions' => [
            'card' => [],
            'direct_debit' => [],
            'bank_transfer' => [],
            'payid' => [],
            'cash' => [],
            'external' => [],
            'bnpl' => [],
        ],
        'providers' => [
            'internal' => [
                'webhook_secret' => env('CHATBOT_ECOMMERCE_INTERNAL_PAYMENT_WEBHOOK_SECRET', ''),
            ],
        ],
    ],
    'bnpl' => [
        'enabled' => true,
        'offer_ttl_minutes' => 15,
        'maximum_installments' => 24,
        'require_licensed_provider' => true,
        'state_secret' => env('CHATBOT_ECOMMERCE_BNPL_STATE_SECRET', ''),
        'shopping_modes' => [
            'native' => ['actionable' => true],
            'marketplace_assisted' => ['actionable' => false, 'handoff' => true],
        ],
        'rental_hire' => [
            'rent_enabled' => false,
            'hire_enabled' => true,
            'lease_enabled' => false,
            'other_enabled' => false,
        ],
        'providers' => [
            'afterpay_clearpay' => ['state_secret' => env('CHATBOT_ECOMMERCE_BNPL_AFTERPAY_STATE_SECRET', '')],
            'klarna' => ['state_secret' => env('CHATBOT_ECOMMERCE_BNPL_KLARNA_STATE_SECRET', '')],
            'zip' => ['state_secret' => env('CHATBOT_ECOMMERCE_BNPL_ZIP_STATE_SECRET', '')],
            'affirm' => ['state_secret' => env('CHATBOT_ECOMMERCE_BNPL_AFFIRM_STATE_SECRET', '')],
            'paypal_pay_later' => ['state_secret' => env('CHATBOT_ECOMMERCE_BNPL_PAYPAL_STATE_SECRET', '')],
            'generic' => ['state_secret' => env('CHATBOT_ECOMMERCE_BNPL_GENERIC_STATE_SECRET', '')],
        ],
    ],
    'rental_hire' => [
        'charge_generation_horizon_days' => 30,
        'maximum_generation_periods' => 500,
        'payment_request_ttl_minutes' => 1440,
        'allowed_payment_methods' => ['card', 'direct_debit', 'bank_transfer', 'payid', 'cash', 'external', 'bnpl'],
        'payment_instructions' => [
            'card' => [],
            'direct_debit' => [],
            'bank_transfer' => [],
            'payid' => [],
            'cash' => [],
            'external' => [],
            'bnpl' => [],
        ],
        'account_prefix' => 'RHA',
        'agreement_prefix' => 'AGR',
        'charge_prefix' => 'CHG',
        'payment_prefix' => 'PAY',
        'adjustment_prefix' => 'ADJ',
        'receipt_prefix' => 'RCP',
    ],
    'pricing' => [
        'prices_include_tax' => false,
        'default_tax_rate_bps' => 0,
        'shipping_tax_rate_bps' => 0,
        'tax_rates' => [],
        'coupon_reservation_ttl_minutes' => 30,
        'snapshot_retention_days' => null,
    ],
    'uninstall' => ['preserve_data' => true],
];
